-- begin TASKTRACK_TASK
alter table TASKTRACK_TASK add constraint FK_TASKTRACK_TASK_ON_ASSIGNEE foreign key (ASSIGNEE_ID) references SEC_USER(ID)^
create unique index IDX_TASKTRACK_TASK_UNIQ_NUMBER_ on TASKTRACK_TASK (NUMBER_) ^
create index IDX_TASKTRACK_TASK_ON_ASSIGNEE on TASKTRACK_TASK (ASSIGNEE_ID)^
-- end TASKTRACK_TASK
-- begin TASKTRACK_TASK_MESSAGE
alter table TASKTRACK_TASK_MESSAGE add constraint FK_TASKTRACK_TASK_MESSAGE_ON_TASK foreign key (TASK_ID) references TASKTRACK_TASK(ID)^
alter table TASKTRACK_TASK_MESSAGE add constraint FK_TASKTRACK_TASK_MESSAGE_ON_IMAP_MESSAGE foreign key (IMAP_MESSAGE_ID) references IMAP_MESSAGE(ID)^
create index IDX_TASKTRACK_TASK_MESSAGE_ON_TASK on TASKTRACK_TASK_MESSAGE (TASK_ID)^
create index IDX_TASKTRACK_TASK_MESSAGE_ON_IMAP_MESSAGE on TASKTRACK_TASK_MESSAGE (IMAP_MESSAGE_ID)^
-- end TASKTRACK_TASK_MESSAGE
-- create sequence
CREATE SEQUENCE seq_un_task START WITH 1 INCREMENT BY 1
-- end sequence
